name: Windows CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, synchronize]    # Rebuild on new pushes to PR

env:
  PIP_VER: "20.2.2"
  WHEEL_VER: "0.35.1"
  PYTEST_VER: "6.0.1"
  SCIPY_VER: "1.4.1"       # Needed by Tensorflow 2.3.0

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        SHARED: [ON, OFF]
        STATIC_RUNTIME: [ON, OFF]
        CONFIG: [Release, Debug]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Config
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX="C:\Program Files\Open3D" -DBUILD_SHARED_LIBS=${{ matrix.SHARED }} -DSTATIC_WINDOWS_RUNTIME=${{ matrix.STATIC_RUNTIME }} ..
      - name: Build
        # cmake --build . --parallel 2 --verbose --config ${{ matrix.CONFIG }} --target INSTALL
        run: |
          cd build
          cmake --build . --parallel 2 --verbose --config ${{ matrix.CONFIG }} --target 3rdparty_tbb
          dir /a-D /S /B tbb\src\ext_tbb-build
          dir /a-D /S /B mkl_install
      - name: Install Python package
        run: |
          python -m pip install --upgrade pip==${{ env.PIP_VER }}
          python -m pip install -U wheel==${{ env.WHEEL_VER }}
          cd build
          cmake --build . --config ${{ matrix.CONFIG }} --target install-pip-package
